### PR TITLE
Dashboard integration

### PR DESCRIPTION
**Pull request by ronanfitz**

### CODE REVIEW

**Comment by HamidAghdaee** [comment]
This looks great @ronanfitz Have you published it and tested it in the dashboard-spa? In which case I would also expect a PR for that repo. thanks.

**Comment by ronanfitz** [comment]
I have already published and tested it in the dashboard with the current pull request.

**Comment by HamidAghdaee** [comment]
@ronanfitz great. Then I would expect another PR with changes to dashboard-spa with regards to importing github-spa and working with it. Unless if those changes are already there. thanks.

**Comment by HamidAghdaee** [comment]
@ronanfitz almost all the tests fail on your branch

**Pull request merged**
